### ISSUE TITLE
Fill out 'examples' stubs

### ISSUE THREAD

**Issue by patrickmj** [omeka/Documentation#32]
We've had stub pages for examples of global functions forever, but few are filled in. Any examples creating behavior beyond the defaults in core themes will be very helpful. They're in `https://github.com/omeka/Documentation/tree/master/source/Reference/libraries/globals/examples` 

Please submit pull requests, and comment on this issue to ask any questions.

**Comment by jaguillette** [comment]
Some colleagues and I submitted this PR as part of a regular coding get-together to pitch in on the Docathon: https://github.com/omeka/Documentation/pull/34

**Comment by patrickmj** [comment]
Thanks! Pulling them in now!
