### ISSUE TITLE
Documentation goes to quick too deep

### ISSUE THREAD

**Issue by modir** [omeka/Documentation#35]
It would be great if there is an introduction section where you talk about directory structure, coding style, frameworks and libraries used and other "general" topics. E.g it would be great to know from the beginning which [standards](http://www.php-fig.org/psr/) from the PHP FIG you are following. This makes it a lot easier to get into the code.

**Comment by teo1978** [comment]
Actually the Developer Documentation is... well, it can't even be called "documentation".

There are just a few ridiculous tutorials like "Plugins Basics" that just give you a very remote idea of how plugins work (not even close to understanding how to write one from scratch), and then a reference where you would look stuff up when you already perfectly know how things work. There's no in-between.

I, as an experienced PHP developer who has worked with a few different frameworks, succesfully developing whole projects based on a framework, or writing plugins for existing ones, am reading the Omeka Developer Documentation and I am just completely lost as if I had read nothing. I need to write just a tiny plugin that does very simple stuff and I have no f***ing clue where to start from. And I start reading the tutorials and at times I feel like I have skipped one before, and at times like the next one is missing. It's a f***ing joke, really.

I'll figure it out more quickly by reverse-engineering existing plugins and looking at Omeka's source code. It's pathetic.

I wonder if there exists a single plugin that has been written by people that are not among the authors or contributors of Omeka's core source code.

End of rant.

**Comment by zerocrates** [comment]
@teo1978

The last time you filed an issue with us several months ago I responded and asked that you keep things constructive. I see you've chosen to go in a... different direction.

Nowhere in your self-described rant do you actually provide enough specific information that even someone that was for some reason still inclined to be helpful after reading it could hope to do so. Concrete suggestions or yes, complaints, are welcome. Simply asking direct questions about things you can't find the answers to is welcome on the forums. This kind of behavior, is not.

**Comment by teo1978** [comment]
I didn't expect to be welcome.

I was hoping to open your eyes. Because by reading that thing that you call documentation, I get the impression that you would expect a developer to be able to start writing a plugin by reading that. And I'm not sure how aware you are of this, but that is NOT the case. Not even close. 

If there was something, that got me somewhere, and then I got stuck because something in particular is missing, I could be more specific or concrete. But I cannot be because the insufficiency of the so-called documentation is itself so broad.

As a somewhat more concrete suggestion: what about a tutorial that shows how to write some kind of "hello world" plugin from scratch?

**Comment by teo1978** [comment]
Is this a bit more specific? 
https://github.com/omeka/Documentation/issues/45

**Comment by modir** [comment]
@teo1978  and @zerocrates  please do not misuse my issue for personal discussions. There are even issues from 2012 open where it is mentioned that the documentation needs more content. I gave as well some detailed information about what I would need. So it is very clear from everyone outside that nobody working for this project really cares about documentation.
So the only options you have is to read the code or open an issue (like I did) and then wait several years till your issue gets answered.

**Comment by sharonmleon** [comment]
We certainly appreciate your concerns about the developer documentation, but frankly, the situation is one of competing priorities and deliverables, and not the fact that "nobody working for this project really cares about documentation." For the first ten years of its life, Omeka was supported nearly completely but grants that demanded that their outcomes and timelines take precedent. Now, with some stable funding, the equivalent staff of 2.5 fulltime people support, maintain, and extend two full code bases (Omeka Classic and Omeka S), 75 addons for those systems, and a hosted system (Omeka.net), and userbase with 100s of thousands of people who are generally technological novices, which means that a significant amount of time goes into offering support through the forums. So, it's not that we don't care, it's that we're pulled in a lot of different directions with relatively few resources.

**Comment by modir** [comment]
@zerocrates My issue was about general documentation not about plugins. You closed this issue now with a commit about plugin development. Please open it again or reference to where my questions get answered.

**Comment by teo1978** [comment]
LOL even for plugins alone, do you seriously consider that  addition to the plugin directory structure to fix the issue of nonexistent plugin development documentation?? Or am I missing some other commit that was not referenced?

**Comment by modir** [comment]
@teo1978 Please open your own issue. There shouldn't be an issue about two topics.
