### ISSUE TITLE
Incorrect hook name for admin_general_settings_form

### ISSUE THREAD

**Issue by EMAN-Omeka** [omeka/Documentation#37]
This [page](http://omeka.readthedocs.io/en/latest/Reference/hooks/admin_general_settings_form.html) incorrectly documents the hook.

For it to work, you have to implement a hook called admin_settings_form (without the 'general'). It then gets correctly called.

Also, the documentation is lacking about the right way to modify the form, but it's another problem.

**Comment by zerocrates** [comment]
It's even a little better... there's _both_ `admin_settings_form`, as you say, _and_ `general_settings_form`, the second one is fired in the controller rather than the view.
