### ISSUE TITLE
Does the API for getting tours info exist?

### ISSUE THREAD

**Issue by drphamwit** [omeka/Documentation#49]
Hi there,

We need to get tour info but do not see what API to call from the document. Does the API actually exist or not?

Thanks,

**Comment by sharonmleon** [comment]
I suspect that this is actually a question for the folks at [Curatescape](https://github.com/CPHDH/Curatescape), since the Omeka Classic core software does not include Tours functionality.

**Comment by drphamwit** [comment]
> I suspect that this is actually a question for the folks at [Curatescape](https://github.com/CPHDH/Curatescape), since the Omeka Classic core software does not include Tours functionality.

Thanks for your prompt response! I will ask folks at Curatescape.

**Comment by sharonmleon** [comment]
Our pleasure.
